core/urls.py
from django.urls import re_path, path, include
from core import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r"export_files", views.ExportFileView) # reportes exportados
router.register(r"product_storage", views.ProductStorageView) # almacenes
router.register(r"store_users", views.StoreUsersView)
router.register(r"user_payments", views.UserPaymentView)
router.register(r"assistance", views.FreelanceAssistance)
router.register(r"assistance_export", views.FreelanceAssistanceExport)
router.register(r"user_messages", views.UserChatViewSet)
router.register(r"message", views.ChatViewSet)
router.register(r"external_payment", views.ExternalPaymentViewsSet)
router.register(r"notifications", views.NotificationView)
router.register(r"product_orders", views.ProductOrderView)
router.register(r"client_order", views.ClientOrderViewSet)
router.register(r"order", views.OrderViewSet)
router.register(r"order_export", views.OrderViewSetExport)
router.register(r"cart", views.CartItemViewSet)
router.register(r"contact_export", views.ContactViewSetExport)
router.register(r"contact", views.ContactViewSet)
router.register(r"review", views.ReviewViewSet)
router.register(r"wishlist", views.WishListViewset)
router.register(r"store", views.StoreViewSet)
router.register(r"product", views.ProductViewSet)
router.register(r"store_product", views.PrivateStoreProductViewSet)
router.register(r"store_product_export", views.PrivateStoreProductExport)
router.register(r"user", views.UserConfigView)
router.register(r"category", views.CategoryViewset)
router.register(r"brand", views.BrandViewset)
router.register(r"regions", views.RegionModelViewSet)
router.register(r"subregions", views.CustomSubRegionView)
router.register(r"cities", views.CustomCityView)
router.register(r"same_user", views.SelfUserViewSet)
router.register(r"media", views.MediaViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('test/', views.TestWebSocketView.as_view()),
    path('send_gc/', views.SendGiftCardView.as_view()),
    path('most_sold/', views.MostSoldProductView.as_view()),
    path('max_price_product/', views.MaxPriceProduct.as_view()),
    path("register/", views.UserRegisterViewSet.as_view()),
    path('user_info/', views.UserInfoView.as_view()),
    path('payment/', views.PaymentView.as_view({"post":"post"})),
    path('paypal/orders/<str:paypal_order_id>/capture/', views.PaypalCaptureOrder.as_view()),
    path('chart/', views.HistoricSalesView.as_view()),
    path('chart_export/', views.HistoricSalesViewExport.as_view()),
    path('assistance_messages/', views.AssistanceMessages.as_view()),
    path("freelancers_stats/", views.FreelanceStatsView.as_view()),
    path('manual_mark_paid_order/',views.ManualMarkOrderPaid.as_view()),
    path('invited_user/', views.AdminCreateInvitedUserView.as_view())
    # path('login/', )
]

multistore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.contrib.staticfiles.views import serve
from store import views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    re_path(r'^cities_light/api/', include('cities_light.contrib.restframework3')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path("api/", include("core.urls")),
    path("api/auth/", include("jwtauth.urls")),
    path('', lambda req: redirect('/store/')),
    path("store/", include("store.urls")),
    path("store-admin/", include("store_admin.urls")),
    path("login/", views.StoreLoginView.as_view(), name="login"),
    path("logout/", views.StoreLogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += [ re_path(r'^static/(?P<path>.*)$', serve), ] 

core/models/assistance.py
from django.db import models
# from core.models.product_order import CartItem,ProductOrder
from django.contrib.auth import get_user_model

User = get_user_model()

class Assistance(models.Model):
    # cart_items = models.ManyToManyField(CartItem)
    # product_orders = models.ManyToManyField(ProductOrder)
    customer = models.ForeignKey(User, related_name="customer_assistances", null=True, on_delete=models.CASCADE)
    feedback = models.BooleanField(null=True)
    freelance = models.ForeignKey(User, related_name="assistances",  on_delete=models.CASCADE)
    completed = models.BooleanField(default=False, help_text="Para indicar si el freelance completo la asistencia")

core/models/brand.py
from django.db import models
from django.utils.timezone import now
from core.models.category import Category


class Brand(models.Model):
    """
    Modelo que representa una marca en el sistema para un producto
    """
    name = models.CharField(max_length=255,help_text="Nombre de la marca")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de creacion de la marca")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion de datos")

    def __str__(self):
        return self.name
    
    @property
    def product_count(self) -> int:
        """
        Propiedad para contar los productos de la categoria
        """
        return self.products.all().count

core/models/cart.py
from django.db import models
from django.contrib.auth import get_user_model
from core.utils.model_choices import OrderStatusChoices
import uuid

User = get_user_model()
class Cart(models.Model):
    """
    Modelo para representar un carrito de compras del usuario
    """
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="cart", help_text="Usuario a quien pertenece el carrito")
    sub_total = models.FloatField(default=0, help_text="Subtotal de los productos del carrito")
    total = models.FloatField(default=0, help_text="Total del producto del carrito")

    @property
    def total_order(self):
        return self.cart_items.all().aggregate(
            total=models.Sum(models.F("product__price")*models.F("quantity"), output_field=models.DecimalField(decimal_places=2))
             ).get("total") or 0

core/models/category.py
from django.db import models
from django.utils.timezone import now



class Category(models.Model):
    """
    Modelo que representa la categoria de un producto o una empresa.
    """
    name = models.CharField(max_length=255, help_text="Nombre de la categoria")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de creacion de la categoria")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion del la categoria")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, help_text="categoria padre de esta categoria")
    def __str__(self):
        return self.name
    

    def get_full_path(self):
        route = []
        new_instance = self
        while new_instance.parent:
            route.append(new_instance.parent.name)
            new_instance = new_instance.parent
        route.append(self.name)
        return route

core/models/config.py
from django.db import models



class Config(models.Model):
    """
    Modelo para representar la configuracion de la tienda,aspecto de la misma.
    """
    main_color = models.CharField(max_length=100, null=True, help_text="Color principal con el que se caracteriza la tienda")
    secondary_color = models.CharField(max_length=100, null=True, help_text="Color secundario con el que se caracteriza la tienda")
    whatsapp_number = models.CharField(max_length=100,null=True, help_text="Numero que aparecera en el icono de whatsapp de la tienda")

core/models/export_file.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth import get_user_model

User = get_user_model()


class ExportFile(models.Model):
    file = models.FileField(upload_to="exports/")
    created_at = models.DateTimeField(auto_now_add=now)
    filename = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering= ["-created_at"]

core/models/external_payments.py
from django.db import models
from django.utils.timezone import now
from core.utils.model_choices import PaymentMethodChoices,NationalBankChoices,ExternalPaymentStatus
from core.models.order import Order

class ExternalPayment(models.Model):
    """
    Modelo que sirve para guardar pagos secundarios de ordenes,
    tales como pagos moviles, o transferencias.
    """
    payment_id = models.CharField(unique=True, max_length=255)
    payment_type = models.CharField(choices=PaymentMethodChoices.CHOICES, max_length=255)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="external_payments")
    national_bank = models.CharField(max_length=255, choices=NationalBankChoices.CHOICES, null=True)
    state = models.CharField(choices=ExternalPaymentStatus.CHOICES, max_length=255, default=ExternalPaymentStatus.REVIEW)
    created_at = models.DateTimeField(auto_now_add=now)
    updated_at = models.DateTimeField(auto_now=now)

core/models/gc_model.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class GiftCard(models.Model):
    code = models.CharField(max_length=255, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

core/models/media.py
from django.db import models
from django.utils.timezone import now

class Media(models.Model):
    """
    Modelo para representar archivos multimedia que pertenezca a alguna entidad del sistema
    """
    name = models.CharField(max_length=255, help_text="Nombre del archivo")
    file = models.FileField(upload_to="media/", help_text="Ruta relativa del archivo")
    priority = models.SmallIntegerField(default=0,help_text="campo para ordernar los archivos de acuerdo a una prioridad")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de subida del documento")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion")

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["priority"]

core/models/notificacions.py
from django.db import models
from django.utils.timezone import now

class EntityChoices:
    ORDER = "order"
    PRODUCT_ORDER = "product_order"
    MESSAGE = "message"
    CHOICES = [
        (ORDER, "Orden"),
        (MESSAGE, "Mensaje"),
        (PRODUCT_ORDER, "Orden de Producto")
    ]

class ChannelGroup(models.Model):
    """
    Group para comunicacion de Channels
    """
    name = models.CharField(unique=True, max_length=500)


class Notification(models.Model):
    """
    Modelo para una notificacion push por channels
    """
    entity_name = models.CharField(max_length=255, choices=EntityChoices.CHOICES)
    message = models.TextField(max_length=1500)
    entity_id = models.PositiveBigIntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=now)
    updated_at = models.DateTimeField(auto_now=now)
    channel_group = models.ForeignKey(ChannelGroup, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering= ["-created_at"]

core/models/order.py
from typing import Iterable, Optional
from django.db import models
from core.utils.model_choices import OrderStatusChoices, PaymentMethodChoices, DeliveryTypeChoices
from django.contrib.auth import get_user_model
import uuid
from django.utils.timezone import now
from core.models.user_data.address import Address

User = get_user_model()

class Order(models.Model):
    """
    Modelo para las ordenes relacionadas a muchos Product Order
    """
    id = models.AutoField(primary_key=True)
    payment_status = models.CharField(choices=OrderStatusChoices.CHOICES,default=OrderStatusChoices.AWAITING_PAYMENT,max_length=255,help_text="Campo para saber el status de la Transaccion")
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Usuario que creo la orden")
    external_payment_id = models.CharField(max_length=255,null=True, help_text="Las procesadoras de pago generan un id externo cuando se hace una compra, ese id debe guardarse aqui")
    payment_method = models.CharField(max_length=255, choices=PaymentMethodChoices.CHOICES, help_text="metodo elegido para el pago")
    receipt = models.FileField(null=True,upload_to="media/", help_text="Campo para hacer referencia a la ubicacion relativa del archivo del recibo de compra")
    delivery_type = models.CharField(max_length=100, choices=DeliveryTypeChoices.CHOICES, default=DeliveryTypeChoices.PERSONALLY, help_text="Campo para saber como el cliente va a retirar la mercancia")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de la Compra")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion de la compra")
    total_amount = models.FloatField(default=0, help_text="monto total de la orden de compra")
    address = models.ForeignKey(Address, null=True, on_delete=models.PROTECT, help_text="Direccion de Envío de la orden")
    aditional_info = models.TextField(max_length=1000, null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        
    def save(self, *args, **kwargs):
        if self.payment_status == OrderStatusChoices.PAYMENT_SUCCESS and not self.external_payment_id and not self.external_payments.exists():
            raise ValueError("No se le puede asignar un status exitoso a una orden si no tiene un id de pasarela de pago (external_payment_id), o algun pago externo asociado (external_payments)")
        return super().save(*args,**kwargs)
    
    @property
    def is_order_paid(self):
        return self.payment_status == OrderStatusChoices.PAYMENT_SUCCESS
    @property
    def total_order(self):
        return self.product_orders.all().aggregate(
            total=models.Sum(models.F("product__price")*models.F("quantity"), output_field=models.FloatField())
             ).get("total", 0) or 0

core/models/password_token.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth import get_user_model
import uuid

User = get_user_model()


class PasswordToken(models.Model):
    token=models.UUIDField(default=uuid.uuid4())
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=now())

    @property
    def still_valid(self):
        print("segundos del token", (now()-self.created_at).seconds)
        return (now()-self.created_at).seconds <= 3*60

core/models/person.py
from django.contrib.auth import get_user_model
from django.db import models
from core.choices.model_choices import PersonType, DocumentType
from .store import Store

User = get_user_model()


class Info(models.Model):
    """
    Modelo de relacion Uno a Uno para guardar informacion adicional del usuario
    """
    person_type = models.CharField(max_length=30, choices=PersonType.CHOICES, help_text="Tipo de persona para saber si es una empresa o una persona natural")
    document_type = models.CharField(max_length=50, choices=DocumentType.CHOICES, help_text="Tipo de documento, si es RIF o cedula")
    document_number = models.CharField(max_length=100, help_text="Numero de identificacion del documento", unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="info", help_text="Usuario al que pertenece la informacion")

core/models/product_storage.py
from django.db import models
from core.models.store import Store
from core.choices.model_choices import ProductStorageChoices


class ProductStorage(models.Model):
    """
    Modelo para el almacen de las tiendas
    al igual que las direcciones, se puede 
    tener varios almacenes, de tipo
    - Tienda Fisica
    - Almacen
    """
    storage_type = models.CharField(max_length=255, choices=ProductStorageChoices.CHOICES, default=ProductStorageChoices.TIENDA_FISICA)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    region = models.CharField(max_length=255, null=True, blank=True)
    subregion = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    coordinate_x = models.FloatField(default=0)
    coordinate_y = models.FloatField(default=0)
    zoom = models.FloatField(default=0)

core/models/shipping_info.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class ShippingInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Usuario al que perteneces esta informacion de envio")
    

core/templates/receipt.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}

		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Recibo</title>

		<!-- Invoice styling -->
		<style>
			body {
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				text-align: center;
				color: #777;
			}

			body h1 {
				font-weight: 300;
				margin-bottom: 0px;
				padding-bottom: 0px;
				color: #000;
			}

			body h3 {
				font-weight: 300;
				margin-top: 10px;
				margin-bottom: 20px;
				font-style: italic;
				color: #555;
			}

			body a {
				color: #06f;
			}

			.invoice-box {
				max-width: 800px;
				margin: auto;
				padding: 30px;
				border: 1px solid #eee;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
				font-size: 16px;
				line-height: 24px;
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				color: #555;
			}

			.invoice-box table {
				width: 100%;
				line-height: inherit;
				text-align: left;
				border-collapse: collapse;
			}

			.invoice-box table td {
				padding: 5px;
				vertical-align: top;
			}

			.invoice-box table tr td:nth-child(2) {
				text-align: right;
			}

			.invoice-box table tr.top table td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.top table td.title {
				font-size: 45px;
				line-height: 45px;
				color: #333;
			}

			.invoice-box table tr.information table td {
				padding-bottom: 40px;
			}

			.invoice-box table tr.heading td {
				background: #eee;
				border-bottom: 1px solid #ddd;
				font-weight: bold;
			}

			.invoice-box table tr.details td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.item td {
				border-bottom: 1px solid #eee;
			}

			.invoice-box table tr.item.last td {
				border-bottom: none;
			}

			.invoice-box table tr.total td:nth-child(3) {
				border-top: 2px solid #eee;
				font-weight: bold;
			}

			@media only screen and (max-width: 600px) {
				.invoice-box table tr.top table td {
					width: 100%;
					display: block;
					text-align: center;
				}

				.invoice-box table tr.information table td {
					width: 100%;
					display: block;
					text-align: center;
				}
			}
		</style>
	</head>

	<body>
		

		<div class="invoice-box">
			<table>
				<tr class="top">
					<td colspan="4">
						<table>
							<tr>
								<td class="title">
									
									<img src="{% static 'img/logo.png' %}" style="width: 100%; max-width: 300px" />
								</td>
								
								<td>
									Recibo #: {{order.id}}<br />
									Creado: {{order.created_at}}<br />
									
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="4">
						<table>
							<tr>
								<td>
									MLS Parts Inversiones, C.A<br />
									Autopista Valencia - Tocuyito<br />
									Tocuyito, Edo. Carabobo.
								</td>
								
								<td>
									<strong>Datos del Cliente:</strong>
									<br>
									{{order.user.full_name}}<br />
									{{order.user.email}}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="heading">
					<td>Método de Pago</td>
					<td></td>
					<td></td>
					<td>$</td>
				</tr>

				<tr class="details">
					<td>{{order.get_payment_method_display}}</td>
					<td></td>
					<td></td>
					<td>{{order.total_order}}</td>
				</tr>

				<tr class="heading">
					<td>Item</td>
					<td style=" text-align: center;">Tienda</td>

					<td>Cant.</td>
					<td>Precio</td>
				</tr>
				{% for item in order.product_orders.all %}
				<tr class="item">
					<td>{{item.product.name}}</td>
					<td style=" text-align: center;"><a href="{{item.product.store.store_url}}">{{item.product.store.name}}</a></td>
					<td>{{item.quantity}}</td>
					<td>${{item.product.price}}</td>
				</tr>
				{% if foorloop.last %}
				<tr class="item last">
					<td> year)</td>
					
					<td>$10.00</td>
				</tr>
				{% endif %}
				{% endfor %}

				<tr class="total">
					<td>Total:</td>
					<td></td>
					<td></td>
					<td> ${{order.total_order}}</td>
				</tr>
				<tr>
					<td><br>
						<br>
						</td>
				</tr>
				{% if order.aditional_info %}
				<tr>
					<td><strong>Observaciones:</strong></td>
					<td></td>
					<td></td>
					<td></td>
			
				</tr>
				<tr>
					<td colspan="4">{{order.aditional_info}}</td>
					
			
				</tr>
				{% endif %}
				{% if order.address %}
				<tr>
					<td><strong>Dirección de Entrega:</strong></td>
					<td></td>
					<td></td>
					<td></td>
			
				</tr>
				<tr>
					<td colspan="4">{{order.address.region}}, {{order.address.subregion}}, {% if order.address.city %}{{order.address.city}}, {% endif %}{% if order.address.short_address %}{{order.address.short_address}}{% endif %}</td>
					
					
				</tr>
				{% endif %}
				
			</table>
			
		</div>
	</body>
</html>