core/urls.py
from django.urls import re_path, path, include
from core import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r"export_files", views.ExportFileView) # reportes exportados
router.register(r"product_storage", views.ProductStorageView) # almacenes
router.register(r"store_users", views.StoreUsersView)
router.register(r"user_payments", views.UserPaymentView)
router.register(r"assistance", views.FreelanceAssistance)
router.register(r"assistance_export", views.FreelanceAssistanceExport)
router.register(r"user_messages", views.UserChatViewSet)
router.register(r"message", views.ChatViewSet)
router.register(r"external_payment", views.ExternalPaymentViewsSet)
router.register(r"notifications", views.NotificationView)
router.register(r"product_orders", views.ProductOrderView)
router.register(r"client_order", views.ClientOrderViewSet)
router.register(r"order", views.OrderViewSet)
router.register(r"order_export", views.OrderViewSetExport)
router.register(r"cart", views.CartItemViewSet)
router.register(r"contact_export", views.ContactViewSetExport)
router.register(r"contact", views.ContactViewSet)
router.register(r"review", views.ReviewViewSet)
router.register(r"wishlist", views.WishListViewset)
router.register(r"store", views.StoreViewSet)
router.register(r"product", views.ProductViewSet)
router.register(r"store_product", views.PrivateStoreProductViewSet)
router.register(r"store_product_export", views.PrivateStoreProductExport)
router.register(r"user", views.UserConfigView)
router.register(r"category", views.CategoryViewset)
router.register(r"brand", views.BrandViewset)
router.register(r"regions", views.RegionModelViewSet)
router.register(r"subregions", views.CustomSubRegionView)
router.register(r"cities", views.CustomCityView)
router.register(r"same_user", views.SelfUserViewSet)
router.register(r"media", views.MediaViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('test/', views.TestWebSocketView.as_view()),
    path('send_gc/', views.SendGiftCardView.as_view()),
    path('most_sold/', views.MostSoldProductView.as_view()),
    path('max_price_product/', views.MaxPriceProduct.as_view()),
    path("register/", views.UserRegisterViewSet.as_view()),
    path('user_info/', views.UserInfoView.as_view()),
    path('payment/', views.PaymentView.as_view({"post":"post"})),
    path('paypal/orders/<str:paypal_order_id>/capture/', views.PaypalCaptureOrder.as_view()),
    path('chart/', views.HistoricSalesView.as_view()),
    path('chart_export/', views.HistoricSalesViewExport.as_view()),
    path('assistance_messages/', views.AssistanceMessages.as_view()),
    path("freelancers_stats/", views.FreelanceStatsView.as_view()),
    path('manual_mark_paid_order/',views.ManualMarkOrderPaid.as_view()),
    path('invited_user/', views.AdminCreateInvitedUserView.as_view())
    # path('login/', )
]

multistore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.contrib.staticfiles.views import serve
from store import views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    re_path(r'^cities_light/api/', include('cities_light.contrib.restframework3')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path("api/", include("core.urls")),
    path("api/auth/", include("jwtauth.urls")),
    path('', lambda req: redirect('/store/')),
    path("store/", include("store.urls")),
    path("store-admin/", include("store_admin.urls")),
    path("login/", views.StoreLoginView.as_view(), name="login"),
    path("logout/", views.StoreLogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += [ re_path(r'^static/(?P<path>.*)$', serve), ] 

store/urls.py
from django.urls import path
from store import views
from django.conf import settings


urlpatterns = [
    path("", views.StoreView.as_view(), name="main_store_list"),
    path('change_password_final/', views.ChangePasswordFinalStep.as_view(), name='change_password_final'),
    path('change_password_form/', views.TokenChangePassword.as_view(), name='change_password_form'),
    path('change_password/', views.PasswordResetEmailTemplate.as_view(), name='change_password'),
    path('send_link_password/', views.SendPasswordResetLink.as_view(), name='send_link_password'),
    path('password_sent/', views.PasswordSentTemplate.as_view(), name='password_sent'),
    path("assistance/chat/<int:pk>/", views.AssistanceDetailView.as_view(), name="assistance_chat"),
    path("assistance/list/", views.AssistanceView.as_view(), name="assistance_list"),
    path("chat/help/", views.HelpChatView.as_view(), name="help_chat"),
    path("wishlist/", views.WishListView.as_view(), name="wishlist"),
    path("<str:slug_store>", views.StoreView.as_view(), name="store_list"),
    path("<str:slug_store>/product/<slug:product_slug>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("categories/", views.CategoriesView.as_view(), name="categories_list"),
    path("stores/", views.StoreListView.as_view(), name="stores_list"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("order_detail/", views.ProductOrderView.as_view(), name="order_detail"),
    path("order_detail/<str:pk>/", views.ProductOrderView.as_view(), name="order_detail"),
    path("order_list/", views.OrderView.as_view(), name="order_list"),
    # Coinbase vistas de Culminacion
    path("payment_success/", views.CoinbasePaymentView.as_view(), name=settings.COINBASE_SUCCESS_URL_NAME),
    path("payment_canceled/", views.CoinbasePaymentView.as_view(), name=settings.COINBASE_CANCELLED_URL_NAME),
    path("terms/conditions/", views.TermsView.as_view(), name="conditions"),
    path("user/register/", views.UserRegisterView.as_view(), name="user_register"),
    path("add_to_cart/", views.AddItemToCart.as_view(), name="add_to_cart"),
    path("remove_from_cart/", views.RemoveItemFromCart.as_view(), name="remove_from_cart"),
    path("add_to_wish/", views.AddItemToWish.as_view(), name="add_to_wish"),
    path("remove_from_wish/", views.RemoveItemFromWish.as_view(), name="remove_from_wish"),
    # path("remove_cart_item/<int:pk>/", views.DeleteitemFromCart.as_view(), name="checkout"),
]

core/models/brand.py
from django.db import models
from django.utils.timezone import now
from core.models.category import Category


class Brand(models.Model):
    """
    Modelo que representa una marca en el sistema para un producto
    """
    name = models.CharField(max_length=255,help_text="Nombre de la marca")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de creacion de la marca")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion de datos")

    def __str__(self):
        return self.name
    
    @property
    def product_count(self) -> int:
        """
        Propiedad para contar los productos de la categoria
        """
        return self.products.all().count

core/models/category.py
from django.db import models
from django.utils.timezone import now



class Category(models.Model):
    """
    Modelo que representa la categoria de un producto o una empresa.
    """
    name = models.CharField(max_length=255, help_text="Nombre de la categoria")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de creacion de la categoria")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de modificacion del la categoria")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, help_text="categoria padre de esta categoria")
    def __str__(self):
        return self.name
    

    def get_full_path(self):
        route = []
        new_instance = self
        while new_instance.parent:
            route.append(new_instance.parent.name)
            new_instance = new_instance.parent
        route.append(self.name)
        return route

core/models/product.py
from uuid import uuid4
from django.db import models
from core.models.brand import Brand
from core.models.category import Category
from django.utils.text import slugify
from core.models.store import Store
from .media import Media, now
from django.utils.timezone import now
from core.models.product_storage import ProductStorage

class ProductTypeChoices:
    SERVICE = "SERVICE"
    MERCHANDISE = "MERCHANDISE"
    CHOICES = [
        (SERVICE, "SERVICIOS"),
        (MERCHANDISE, "MERCANCIA")
    ]
class ConditionChoices:
    NEW = "NEW"
    USED = "USED"
    REFURBISHED = "REFURBISHED"
    CHOICES = [
        (NEW, "Nuevo"),
        (USED, "Usado"),
        (REFURBISHED, "Remanufacturado")
    ]
class Products(models.Model):
    """
    Modelo que representa a los productos que se almacenan en la base de datos
    """
    name = models.CharField(max_length=255, help_text="Nombre o título del producto")
    product_slug = models.SlugField(max_length=800,unique=True, null=True, help_text="sufijo unico para encontrar el producto por la URL")
    quantity = models.PositiveBigIntegerField(help_text="Cantidad del producto en inventario")
    brand = models.ForeignKey(Brand, null=True, related_name="products",help_text="Marca del producto, si es null se entendera como generica",on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category, help_text="Categoria del producto",on_delete=models.SET_NULL, related_name="products", null=True)
    photos = models.ManyToManyField(Media, help_text="Fotos y/o archivos asociados al producto")
    description = models.TextField(max_length=5000, null=True, help_text="Descripcion corta del producto")
    large_description = models.TextField(max_length=5000, null=True, help_text="Descripcion larga del producto del producto")
    thumbnail = models.ForeignKey(Media, on_delete=models.SET_NULL, null=True, related_name="main_products",help_text="Miniatura del producto")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de creacion del producto")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de actualizacion del producto")
    condition = models.CharField(max_length=255, choices=ConditionChoices.CHOICES, default=ConditionChoices.NEW, help_text="Condicion del producto")
    store = models.ForeignKey(to=Store, help_text="Tienda que publico el producto",on_delete=models.CASCADE, related_name="products")
    product_storage = models.ForeignKey(ProductStorage, on_delete=models.SET_NULL, null=True, help_text='Almacen donde pertenece el producto')
    price = models.FloatField(null=True, help_text="si es null se marcara como gratuito")
    product_type = models.CharField(max_length=200, help_text="determina si un bien es un producto o un servicio, solo los servicios pueden llevar price=null", choices=ProductTypeChoices.CHOICES, default=ProductTypeChoices.SERVICE)
    discount = models.PositiveSmallIntegerField(default=0, help_text="Porcentaje de descuento de un producto, en caso de que lo tenga.")

    class Meta:
        ordering = ["-created_at"]
    def save(self, *args, **kwargs) -> None:
        if self.product_slug: 
            return super().save(*args, **kwargs)
        self.product_slug = f"{slugify(self.name)}{uuid4()}"
        print(self.product_slug)
        return super().save(*args, **kwargs)
    
    @property
    def get_discount(self):
        return self.price - self.price*self.discount/100 if self.discount else None

    @property
    def has_stock(self):
        return bool(self.quantity)

    @property
    def verbose_condition(self):
        return dict(ConditionChoices.CHOICES).get(self.condition)

    @property
    def rating(self):
        if not self.reviews.exists(): return 0
        return round(sum(self.reviews.all().values_list("score", flat=True))/self.reviews.all().count())
        
    def __str__(self):
        return self.name

core/models/store.py
from django.db import models
from django.utils.timezone import now
from core.models.config import Config
from core.models.media import Media
from core.models.category import Category
from django.utils.text import slugify
from core.utils.model_choices import CompanyEmployeeChoices
from django.conf import settings
from django.urls import reverse




class Store(models.Model):
    """
    Modelo que referencia a una tienda dentro del sistema
    """
    name = models.CharField(max_length=255, help_text="Nombre de la tienda")
    slug = models.SlugField(max_length=200, unique=True, help_text="sufijo para ubicar la tienda facilmente por URL")
    logo = models.ImageField(upload_to="uploads/", null=True, help_text="imagen que contiene el logotipo de la empresa")
    description = models.CharField(max_length=500, null=True, help_text="Una breve descripcion de la Empresa")
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL, null=True, help_text="Categoria principal a la que se dedica la empresa")
    parent = models.ForeignKey("self", related_name="parent_store", null=True, on_delete=models.CASCADE, help_text="Referencia a una tienda padre que la haya referenciado o en caso de ser franquicia, la empresa matriz")
    created_at = models.DateTimeField(auto_now_add=now, help_text="Fecha de ingreso al sistema")
    updated_at = models.DateTimeField(auto_now=now, help_text="Fecha de actualizacion de la informacion")
    config = models.OneToOneField(Config, on_delete=models.CASCADE, null=True, help_text="relacion con confoguracion de la Empresa")
    bussiness_legal_id = models.CharField(unique=True, null=True, max_length=255, help_text="Numero de Identificacion Comercial de la empresa, varia dependiendo del pais, EJ: Venezuela, RIF.")
    money = models.FloatField(default=0, help_text="Dinero por retirar de la tienda")
    company_employee_number = models.CharField(choices=CompanyEmployeeChoices.CHOICES, max_length=255, help_text="Numero estimado de empleados de la Empresa.")
    company_anual_income = models.FloatField(null=True, help_text="Ingreso Anual de la empresa Expresado en Dolares, Campo no Obligatorio")

    def save(self, *args, **kwargs):
        self.slug = f"{slugify(self.name)}"
        return super().save(*args, **kwargs)

    @property
    def store_url(self):
        return f"{settings.BASE_URL}{reverse('store_list', args=(self.slug,))}"

    def __str__(self):
        return self.name

core/models/wishlist.py
from django.contrib.auth import get_user_model
from core.models.product import Products
from django.db import models


User = get_user_model()

class Wish(models.Model):
    """
    Modelo que representa un elemento de la lista de deseos
    """
    product = models.ForeignKey(Products, on_delete=models.CASCADE, help_text="Producto agregado a la lista de deseos")
    user = models.ForeignKey(User, related_name="wish_list",help_text="Usuario que agrego este producto a su lista", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} - {self.user.email}"
    
    class Meta:
        constraints= [
            models.UniqueConstraint(fields=["product","user"], name="unique product per user")
        ]

store/models.py
from django.db import models

# Create your models here.

store/templates/store.html
{% extends "base.html" %}
{% load static %}


{% block content %}

		<!-- SECTION -->
		<div class="section">
			
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					
					<div id="aside" class="col-md-3">
						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Categorías</h3>
							<div class="checkbox-filter">
								
									{% for category in category_list %}
										<div class="input-checkbox">
											<input type="checkbox" onclick="setCategoryFilter(event)" value="{{category.id}}" {% if category.id in category_param_list %}checked{% endif %} id="category-{{category.id}}">
											<label for="category-{{category.id}}">
												<span></span>
												{{category.name}}
												<small>({{category.products.count}})</small>
											</label>
										</div>
									{% endfor %}
								
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Precio</h3>
							<div class="price-filter">
								<form onsubmit="setPriceFilter(event)" method="get">
									
									<div id="price-slider"></div>
										<div class="d-flex flex-row">
											<div class="input-number price-min">
												<input id="price-min" name="min_price" type="number">
												<span class="qty-up">+</span>
												<span class="qty-down">-</span>
											</div>
											<span>-</span>
											<div class="input-number price-max">
												<input id="price-max" name="max_price" type="number">
												<span class="qty-up">+</span>
												<span class="qty-down">-</span>
											</div>
										</div>
										<div class="d-grid gap-2 pt-3 mb-2">
											<button class="btn btn-danger" type="submit">Filtrar</button>
										  </div>
										</form>
										<input class="form-check-input" type="checkbox" {% if request.GET.free == 'true' %}checked{% endif %} id="flexCheckDefault" onchange="setFreeFilter(event)" name="allow_free">
										<label class="form-check-label" for="flexCheckDefault">
										Ver productos Gratuitos
										</label>
									</div>
								</div>
								<!-- /aside Widget -->
								
								<!-- aside Widget -->
								<div class="aside">
							<h3 class="aside-title">Marcas</h3>
							<div class="checkbox-filter">
								
								{% for brand in brand_list %}
									<div class="input-checkbox">
										<input type="checkbox" onclick="setBrandFilter(event)" value="{{brand.id}}" {% if brand.id in brand_param_list %}checked{% endif %} id="brand-{{brand.id}}">
										<label for="brand-{{brand.id}}">
											<span></span>
											{{brand.name}}
											<small>({{brand.products.count}})</small>
										</label>
									</div>
								{% endfor %}
								
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Más vendidos</h3>
							
							{% for item in most_sold %}
							<div class="product-widget row border w-100 h-50 mx-0 most_sold__card" onclick="goToProduct('{% url 'product_detail' item.store.slug item.product_slug %}')">
								<div class="d-inline-block p-0 overflow-hidden" style="width: 100px;">
									<img class="responsive-img" src="{{item.thumbnail.file.url}}" alt="">
								</div>
								<div class="product-body w-50 most_sold__text">
									
									<h3 class="product-name mt-2"><a href="{% url 'product_detail' item.store.slug item.product_slug %}">{{item.name}}</a></h3>
									{% if item.price %}
									<h4 class="product-price">$ {{item.price}}</h4>
									{% else %}
									<h4 class="product-price">Gratuito</h4>
									{% endif %}
									<p class="m-0 most_sold__category">{{item.category.name}}</p>
									<!-- <h4 class="product-price">$ [[item.product_details.price]] <del class="product-old-price">$</del></h4> -->
								</div>
							</div>
							{% endfor %}
						</div>
						<!-- /aside Widget -->
					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store top filter -->
						<div class="store-filter clearfix">
							<div class="store-sort">
								<label>
									Ordenar por:
									<select class="input-select" id="order-select" placeholder="Seleccione"onchange="orderBy(event)">
										<option value="popular">Popularidad</option>
										<option value="-created_at">Recientes</option>
										<option value="price">Asc. Precio</option>
										<option value="-price">Desc. Precio</option>
									</select>
								</label>
							</div>
							{% if request.GET %}
							<ul class="store-grid">
								<a href="{% if current_store %}{% url 'store_list' current_store.slug %}{% else %}{% url 'main_store_list' %}{% endif %}" class="btn btn-danger"><i class="fa fa-minus-circle"></i> Borrar filtros</a>
							</ul>
							{% endif %}
						</div>
						<!-- /store top filter -->

						<!-- store products -->
						<div class="row" id="product-list">
							{% for product in object_list %}
							<!-- product -->
							<div class="col-lg-4 col-md-6 col-sm-6 col-xs-6">
									<a href="{% url 'product_detail' product.store.slug product.product_slug %}">
									<div class="product">
										<div class="product-img product-img-store">
											<img src="{% if product.thumbnail %}{{product.thumbnail.file.url}}{% else %}{% static 'img/no-photo.png' %}{% endif %}" alt="">
											<div class="product-label">
												{% if product.get_discount %}<span class="sale">-product.get_discount%</span>{% endif %}
												<span class="new">{{product.get_condition_display}}</span>
											</div>
										</div>
										<div class="product-body">
											<p class="product-category">{{product.category|default_if_none:"Sin Categoría"}}</p>
											<h3 class="product-name"><a href="{% url 'product_detail' product.store.slug product.product_slug %}">{{product.name}}</a></h3>
											<h4 class="product-price">{% if product.price %}${{product.price}}{% else %}Gratis{% endif %}{% if product.get_discount%}<del class="product-old-price">${{product.get_discount}}</del>{% endif %}</h4>
											<div class="product-rating">
												{% for score in score_range %}
													<i class="fa fa-star"></i>
												{% endfor %}
												{% for score in score_range_left %}
													<i class="fa fa-star-o"></i>
												{% endfor %}
											</div>
											<div class="product-btns">
												<button class="add-to-wishlist" onclick="addToWishlist(event,'{{product.id}}')"><i class="fa fa-heart-o"></i><span class="tooltipp">Agregar a lista de deseos</span></button>
												<a href="{% url 'product_detail' product.store.slug product.product_slug %}" class="quick-view"><i class="fa fa-eye"></i></span></a>
											</div>
										</div>
										<div class="add-to-cart">
											<button class="add-to-cart-btn" onclick="addToCart(event, '{{product.id}}')"><i class="fa fa-shopping-cart"></i> {% if product.id in products_cart %} Eliminar del carrito{% else %}Agregar al Carrito{% endif %}</button>
										</div>
									</div>
								</a>
								</div>
								<!-- /product -->

								{% empty %}
								<div class="d-flex flex-column justify-content-center">
									<h4>Ups!</h4>
									<img src="{% static 'img/no_results.svg' %}" class="w-25" alt="">
									<h4 class="pt-2">Sin resultados</h4>
								</div>
							{% endfor %}
						</div>
						<!-- /store products -->

						<!-- store bottom filter -->
						<div class="store-filter clearfix">
							<span class="store-qty">Mostrando 20-{{object_count}} productos</span>
							<ul class="store-pagination">
								{% for pages in page_obj.paginator %}
									{% if pages.number == page_obj.number %}
										<li class="active">{{pages.number}}</li>
									{% else %}
										<li><a href="{% if current_store %}{% url 'store_list' current_store.slug %}{% else %}{% url 'main_store_list' %}{% endif %}?page={{pages.number}}&{% for query,value in request.GET.items %}{% if query != 'page' %}{{query}}={{value}}&{% endif %}{% endfor %}">{{pages.number}}</a></li>
										<!-- <li><a href="#"><i class="fa fa-angle-right"></i></a></li> -->
									{% endif %}
								{% endfor %}
							</ul>
						</div>
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
		<script>
			axios.defaults.xsrfHeaderName = 'X-CSRFToken';
			axios.defaults.xsrfCookieName = 'csrftoken';
			document.addEventListener("DOMContentLoaded", function(){
				let order_select = document.querySelector("#order-select");
				const url = new URL(window.location.href);
				let value = url.searchParams.get("o");
				order_select.value = value !== null ? value : "popularity";
			})
			const data = {
				order_by: null,
				modal_message: null,
				login_url:"{% url 'login' %}"
			}
			// const app = new Vue({
			// 	el:"#aside-app",
			// 	delimiters: ["[[","]]"],
			// 	data(){
			// 		return {
			// 			items : [],
			// 			count: 0,
			// 			loading: true,
			// 			no_result_img: "{% static 'img/no-photo.png' %}"
			// 		}
			// 	},
			// 	methods:{
			// 		getImageSize(img_url){
			// 			let img = new Image();
			// 			img.src = img_url
			// 			return img.height
			// 		}
			// 	},
			// 	mounted(){

			// 		axios.get("/api/most_sold/")
			// 		.then((res)=>{
			// 			console.log(res.data)
			// 			this.items = res.data
			// 			this.loading = false
			// 		})
			// 	}
			// })
			function addToCart(event, product_id){
				axios.post("/api/cart/",{product: product_id, quantity: 1}, {withCredentials:true})
				.then((data)=>{
					if(data.status == 201){
						let modal_body = document.querySelector("#modal-body");
						modal_body.innerHTML = `<p>Producto Agregado a tu Carrito!</p>`
						const myModalAlternative = new bootstrap.Modal('#Modal')
						myModalAlternative.show()
						event.target.innerText = "Eliminar del carrito";
					}else if(data.status == 204){
						let modal_body = document.querySelector("#modal-body");
						modal_body.innerHTML = `<p>Producto Eliminado de tu Carrito!</p>`
						const myModalAlternative = new bootstrap.Modal('#Modal')
						myModalAlternative.show()
						event.target.innerText = "Agregar al carrito";
					}
				})
				.catch((error)=>{
					console.log(error);
					data.modal_message = error;
					let modal_body = document.querySelector("#modal-body");
					modal_body.innerHTML = `<p>${Object.entries(error.response.data)}</p>`
					if (error.response.data.message || error.response.data.non_field_errors){
						modal_body.innerHTML = `<p>${error.response.data.message || error.response.data.non_field_errors}</p>`

					}
					const myModalAlternative = new bootstrap.Modal('#Modal');
					myModalAlternative.show();
				})
				.finally((res)=>{
					getCartItems();
				})
			}
			function addToWishlist(event, product_id){
				axios.post("/api/wishlist/",{product_id: product_id}, {withCredentials:true})
				.then((data)=>{
					console.log(data.data);
					let modal_body = document.querySelector("#modal-body");
					modal_body.innerHTML = `<p>Producto Agregado a tu lista de deseos!</p>`
					const myModalAlternative = new bootstrap.Modal('#Modal')
					myModalAlternative.show()
					
					getWishList()
				})
				.catch((error)=>{
					console.log(error);
					data.modal_message = error;
					let modal_body = document.querySelector("#modal-body");
					modal_body.innerHTML = `<p>${error.response.data}</p>`
					const myModalAlternative = new bootstrap.Modal('#Modal');
					myModalAlternative.show();
					
				})
			}

			function setCategoryFilter(event){
				let category = event.target.value;
				let url = new URL(window.location.href);
				if (event.target.checked){
					url = getOrSetParam("category", category);
				}else {
					url = removeParam("category", category);
				}
				
				window.location.href = url;
			}
			function setPriceFilter(event){
				event.preventDefault();
				console.log(event.target);
				let min_price = event.target.min_price.value;
				let max_price = event.target.max_price.value;

				let url = new URL(window.location.href);
				url = getOrSetParam("min_price", min_price, false, true);
				url = getOrSetParam("max_price", max_price, url, true);
				
				
				window.location.href = url;
			}
			function setBrandFilter(event){
				let brand = event.target.value;
				let url = new URL(window.location.href);
				if (event.target.checked){
					url = getOrSetParam("brand", brand);
				} else {
					url = removeParam("brand", brand);
				}
				
				
				window.location.href = url;
			}
			function setFreeFilter(event){
				let free = event.target.checked.toString();
				let url = new URL(window.location.href);
				url = getOrSetParam("free", free, url, true);
				window.location.href = url;
			}

			function orderBy(event){
				const url = new URL(window.location.href);
				url.searchParams.set("o",event.target.value);
				window.location.href = url;
			}
			function goToProduct(url){
				window.location.href = url;
			}

		</script>
		
{% endblock %}
		